repos:
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile=black, --line-length=80]
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--line-length=80]
    language_version: python3.10
- repo: https://github.com/pycqa/flake8
  rev: '4.0.1'
  hooks:
  - id: flake8
    args: [--config=.flake8]
